(TeX-add-style-hook "Chapter09"
 (lambda ()
    (LaTeX-add-index-entries
     "succession"
     "Buell-Small"
     "competition--colonization tradeoff|see{tradeoffs}"
     "tradeoffs!competition--colonization"
     "metapopulation!propagule rain, estimation"
     "pioneer species"
     "climax species"
     "landscape mosaic"
     "habitat destruction"
     "Cedar Creek Natural History Area"
     "Schizachyrium@\\emph{Schizachyrium scoparium}"
     "Andropogon@\\emph{Andropogon gerardii}"
     "bluestem"
     "R@$R^*$"
     "extinction debt"
     "r-selected"
     "tradeoffs!competition--maximum~growth~rate"
     "successional niche"
     "finite rate of competitive exclusion"
     "susceptible|see{successional niche, SIR models}"
     "resistant|see{successional niche, SIR models}"
     "$\\gamma$|see{successional niche, SIR models}"
     "storage effect"
     "buffered population growth"
     "environment--competition covariation"
     "lottery models"
     "covariance|see{environment--competition covariation}"
     "CV@$CV$|see{coefficent of variation}"
     "coefficent of variation"
     "specialization"
     "niche overlap"
     "temporal niche")
    (LaTeX-add-labels
     "fig:bssucc"
     "eq:cc1a"
     "eq:cc2"
     "eq:3"
     "eq:4"
     "eq:5"
     "eq:eq2"
     "eq:cc7"
     "eq:ccint2"
     "ccnoint"
     "ccint"
     "fig:cc"
     "eq:9"
     "eq:cc10"
     "eq:cc11"
     "eq:col"
     "ranks"
     "ccdyn"
     "fig:mhd"
     "fig:PR"
     "eq:sn1"
     "fig:SPR"
     "fig:SPR1"
     "fig:SPR2"
     "fig:SPR3"
     "fig:SPR4"
     "fig:ED1"
     "fig:ED2"
     "fig:EDSN"
     "eq:storage"
     "rho"
     "Eenv"
     "fig:rho"
     "fig:storedyns1"
     "eq:compnu"
     "beta1"
     "betaE"
     "fig:chess")))

