# Multiple Basins of Attraction

## Introduction
Historically, simple models may have helped to lull some ecologists into thinking either that (i) models are useless because they do not reflect the natural
world, or (ii) the natural world is highly predictable. Here we investigate how simple models can create unpredictable outcomes, in models of Lotka--Volterra competition, resource competition, and intraguild predation. In all cases, we
get totally different outcomes, or alternative stable states, depending on
different, stochastic, initial conditions.

## Alternative stable states
*Alternative stable states* (ASS), *are a set of two or more possible stable attractors that can occur given a single set of external environmental conditions*.  For a single list of species, there may exist more than one set of abundances that provide stable equilibria. One key to assessing alternative stable states is that *the stable states must occur with the same external environmental conditions*. If the external conditions differ, then the system is merely governed by different conditions. A very important complication is that if an abiotic factor is coupled dynamically to the biotic community, then it becomes by definition an internal part of the system and no longer external to it.

If stable attractors exist, how does the system shift from one attractor to another? The system can be shifted in a variety of ways, but the key is that the system (i.e., the set of species abundances) gets shifted into a different part of the state space, and then is attracted toward another state. System shifts may occur due to demographic stochasticity, the random variation in births and deaths that may be especially important when populations become small. System shifts may also occur due to different assembly sequences. For instance the outcome of succession may depend upon which species arrive first, second, third, etc. System shifts might also arise via a physical disturbance that causes mortality. Different abundances may also arise from the gradual change and return of an environmental factor, and the resulting set of alternative equilibria is known as *hysteresis*, and below we examine a case related to resource competition. 