# Populations in space

## Source-sink Dynamics
In Chapters 1-3, we considered *closed* populations. In contrast, one could imagine a population governed by *b*irths plus *i*mmigration, and *d*eaths plus *e*migration (a *BIDE* model). Ron Pulliam [@Pulliam:1988ez] proposed a simple model that includes all four components of *BIDE* which provides a foundation for thinking about connected subpopulations. We refer to the dynamics of these as *source-sink dynamics*. Examples of such linked populations might include many different types of species. For instance, a source-sink model could describe linked populations of a single species might occupy  habitat patches of different quality, where organisms might disperse from patch to patch.

```{r fig.cap='Two subpopulations linked with movement'}
ss <- matrix(c(NA, expression("e"[12]=="i"[21]), 
               expression("e"[21]=="i"[12]), NA), nc=2)

ss <- matrix(c(NA, "e[12]==i[21]", "e[21]==i[12]", NA), nc=2, byrow=TRUE)
colnames(ss) <- rownames(ss) <- c("Pop 1", "Pop 2")
ss
plotmat(ss,pos=c(2))
```

### Balanced dispersal

* i12=i21
* Requires that the proportion of the population migrating is lower in larger habitats, higher in smaller patches
     * Size-contingent dispersal startegy (McPeek and Holt 1992)
     * Higher edge:area ratio (Hambeck, Crist, et al. 2007)
* example Diffendorfer (1998) Balanced dispersal in small mammals.
    * Proportion migrating was size-dependent
    * 
     


### Habitat selection
ideal-despotic and ideal-free distributions   

## Metapopulations

$$\dot{p} = cp - cp^2 -ep = (c-e)p(1-p)$$

$$\dot{p} = cp - cp^2 - ep + ep^2$$

rate of change = fecundity x open patches 

$$\dot{p} = fp(1-p) - ec$$



Glanville Fritillary Butterfly (Hanksi 1999, Ojanen et al. 2013)