<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>14 Appendix | Primer of Ecology using R</title>
  <meta name="description" content="14 Appendix | Primer of Ecology using R" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="14 Appendix | Primer of Ecology using R" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="HankStevens/Primer-of-Ecology" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="14 Appendix | Primer of Ecology using R" />
  
  
  

<meta name="author" content="Hank Stevens" />


<meta name="date" content="2020-11-21" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="diversity.html"/>
<link rel="next" href="references.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i><b>0.1</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="theory.html"><a href="theory.html"><i class="fa fa-check"></i><b>1</b> Theory in Ecology</a><ul>
<li class="chapter" data-level="1.1" data-path="theory.html"><a href="theory.html#examples-of-theories"><i class="fa fa-check"></i><b>1.1</b> Examples of theories</a><ul>
<li class="chapter" data-level="1.1.1" data-path="theory.html"><a href="theory.html#hierarchy-theory"><i class="fa fa-check"></i><b>1.1.1</b> Hierarchy theory</a></li>
<li class="chapter" data-level="1.1.2" data-path="theory.html"><a href="theory.html#a-general-theory-of-ecology"><i class="fa fa-check"></i><b>1.1.2</b> A general theory of ecology</a></li>
<li class="chapter" data-level="1.1.3" data-path="theory.html"><a href="theory.html#efficient-theory"><i class="fa fa-check"></i><b>1.1.3</b> Efficient theory</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="theory.html"><a href="theory.html#metabolic_scaling"><i class="fa fa-check"></i><b>1.2</b> An example: Metabolic Theory of Ecology</a><ul>
<li class="chapter" data-level="1.2.1" data-path="theory.html"><a href="theory.html#body-size-dependence"><i class="fa fa-check"></i><b>1.2.1</b> Body-size dependence</a></li>
<li class="chapter" data-level="1.2.2" data-path="theory.html"><a href="theory.html#temperature-dependence"><i class="fa fa-check"></i><b>1.2.2</b> Temperature dependence</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="theory.html"><a href="theory.html#power-law-scaling-implies-constant-relative-differences"><i class="fa fa-check"></i><b>1.3</b> Power law scaling implies constant relative differences</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="oft.html"><a href="oft.html"><i class="fa fa-check"></i><b>2</b> Optimal Foraging</a><ul>
<li class="chapter" data-level="2.1" data-path="oft.html"><a href="oft.html#a-prey-model"><i class="fa fa-check"></i><b>2.1</b> A prey model</a><ul>
<li class="chapter" data-level="2.1.1" data-path="oft.html"><a href="oft.html#our-intuition"><i class="fa fa-check"></i><b>2.1.1</b> Our intuition</a></li>
<li class="chapter" data-level="2.1.2" data-path="oft.html"><a href="oft.html#mathematical-support"><i class="fa fa-check"></i><b>2.1.2</b> Mathematical support</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="oft.html"><a href="oft.html#the-patch-model"><i class="fa fa-check"></i><b>2.2</b> The patch model</a></li>
<li class="chapter" data-level="2.3" data-path="oft.html"><a href="oft.html#a-simulation-of-a-prey-model"><i class="fa fa-check"></i><b>2.3</b> A simulation of a prey model</a><ul>
<li class="chapter" data-level="2.3.1" data-path="oft.html"><a href="oft.html#lab-exercise"><i class="fa fa-check"></i><b>2.3.1</b> Lab exercise</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="expo.html"><a href="expo.html"><i class="fa fa-check"></i><b>3</b> Simple density-independent growth</a><ul>
<li class="chapter" data-level="3.1" data-path="expo.html"><a href="expo.html#discrete-growth-rates-of-fruit-flies-in-my-kitchen"><i class="fa fa-check"></i><b>3.1</b> Discrete growth rates of fruit flies in my kitchen</a></li>
<li class="chapter" data-level="3.2" data-path="expo.html"><a href="expo.html#fruit-flies-with-continuous-overlapping-generations"><i class="fa fa-check"></i><b>3.2</b> Fruit flies with continuous overlapping generations</a></li>
<li class="chapter" data-level="3.3" data-path="expo.html"><a href="expo.html#properties-of-geometric-and-exponential-growth"><i class="fa fa-check"></i><b>3.3</b> Properties of geometric and exponential growth</a><ul>
<li class="chapter" data-level="3.3.1" data-path="expo.html"><a href="expo.html#average-growth-rate"><i class="fa fa-check"></i><b>3.3.1</b> Average growth rate</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="expo.html"><a href="expo.html#modeling-with-data-simulated-dynamics"><i class="fa fa-check"></i><b>3.4</b> Modeling with Data: Simulated Dynamics</a><ul>
<li class="chapter" data-level="3.4.1" data-path="expo.html"><a href="expo.html#data-based-approaches"><i class="fa fa-check"></i><b>3.4.1</b> Data-based approaches</a></li>
<li class="chapter" data-level="3.4.2" data-path="expo.html"><a href="expo.html#creating-and-visualizing-the-data"><i class="fa fa-check"></i><b>3.4.2</b> Creating and visualizing the data</a></li>
<li class="chapter" data-level="3.4.3" data-path="expo.html"><a href="expo.html#one-simulation"><i class="fa fa-check"></i><b>3.4.3</b> One simulation</a></li>
<li class="chapter" data-level="3.4.4" data-path="expo.html"><a href="expo.html#multiple-simulations"><i class="fa fa-check"></i><b>3.4.4</b> Multiple simulations</a></li>
<li class="chapter" data-level="3.4.5" data-path="expo.html"><a href="expo.html#a-distribution-of-possible-futures"><i class="fa fa-check"></i><b>3.4.5</b> A distribution of possible futures</a></li>
<li class="chapter" data-level="3.4.6" data-path="expo.html"><a href="expo.html#analyzing-results"><i class="fa fa-check"></i><b>3.4.6</b> Analyzing results</a></li>
<li class="chapter" data-level="3.4.7" data-path="expo.html"><a href="expo.html#inferring-processes-underlying-growth-rate"><i class="fa fa-check"></i><b>3.4.7</b> Inferring processes underlying growth rate</a></li>
<li class="chapter" data-level="3.4.8" data-path="expo.html"><a href="expo.html#f-environmental-noise"><i class="fa fa-check"></i><b>3.4.8</b> 1/<span class="math inline">\(f\)</span> environmental noise</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="DID.html"><a href="DID.html"><i class="fa fa-check"></i><b>4</b> Density-independent Demography</a><ul>
<li class="chapter" data-level="4.1" data-path="DID.html"><a href="DID.html#a-two-stage-matrix-model"><i class="fa fa-check"></i><b>4.1</b> A two stage matrix model</a></li>
<li class="chapter" data-level="4.2" data-path="DID.html"><a href="DID.html#a-brief-primer-on-matrices"><i class="fa fa-check"></i><b>4.2</b> A brief primer on matrices</a></li>
<li class="chapter" data-level="4.3" data-path="DID.html"><a href="DID.html#decomposing-a"><i class="fa fa-check"></i><b>4.3</b> Decomposing <strong>A</strong></a></li>
<li class="chapter" data-level="4.4" data-path="DID.html"><a href="DID.html#a-three-stage-model"><i class="fa fa-check"></i><b>4.4</b> A three stage model</a></li>
<li class="chapter" data-level="4.5" data-path="DID.html"><a href="DID.html#projection"><i class="fa fa-check"></i><b>4.5</b> Projection</a></li>
<li class="chapter" data-level="4.6" data-path="DID.html"><a href="DID.html#analyzing-the-transition-matrix"><i class="fa fa-check"></i><b>4.6</b> Analyzing the transition matrix</a><ul>
<li class="chapter" data-level="4.6.1" data-path="DID.html"><a href="DID.html#eigenanalysis"><i class="fa fa-check"></i><b>4.6.1</b> Eigenanalysis</a></li>
<li class="chapter" data-level="4.6.2" data-path="DID.html"><a href="DID.html#finite-rate-of-increase"><i class="fa fa-check"></i><b>4.6.2</b> Finite rate of increase</a></li>
<li class="chapter" data-level="4.6.3" data-path="DID.html"><a href="DID.html#stable-stage-distribution"><i class="fa fa-check"></i><b>4.6.3</b> Stable stage distribution</a></li>
<li class="chapter" data-level="4.6.4" data-path="DID.html"><a href="DID.html#calculating-the-stable-stage-distribution"><i class="fa fa-check"></i><b>4.6.4</b> Calculating the stable stage distribution</a></li>
<li class="chapter" data-level="4.6.5" data-path="DID.html"><a href="DID.html#reproductive-value"><i class="fa fa-check"></i><b>4.6.5</b> Reproductive value</a></li>
<li class="chapter" data-level="4.6.6" data-path="DID.html"><a href="DID.html#sensitivity-and-elasticity"><i class="fa fa-check"></i><b>4.6.6</b> Sensitivity and elasticity</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="DID.html"><a href="DID.html#integral-projection"><i class="fa fa-check"></i><b>4.7</b> Integral projection</a><ul>
<li class="chapter" data-level="4.7.1" data-path="DID.html"><a href="DID.html#a-size-based-ipm-of-smooth-coneflower"><i class="fa fa-check"></i><b>4.7.1</b> A size-based IPM of smooth coneflower</a></li>
<li class="chapter" data-level="4.7.2" data-path="DID.html"><a href="DID.html#population-summaries"><i class="fa fa-check"></i><b>4.7.2</b> Population summaries</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="DID.html"><a href="DID.html#r-packges-for-demography"><i class="fa fa-check"></i><b>4.8</b> R packges for demography</a></li>
<li class="chapter" data-level="4.9" data-path="DID.html"><a href="DID.html#exploring-a-real-population"><i class="fa fa-check"></i><b>4.9</b> Exploring a real population</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="DDgrowth.html"><a href="DDgrowth.html"><i class="fa fa-check"></i><b>5</b> Density-dependent growth</a><ul>
<li class="chapter" data-level="5.1" data-path="DDgrowth.html"><a href="DDgrowth.html#continuous-logistic-growth"><i class="fa fa-check"></i><b>5.1</b> Continuous logistic growth</a></li>
<li class="chapter" data-level="5.2" data-path="DDgrowth.html"><a href="DDgrowth.html#dynamics-around-the-equilibria-stability"><i class="fa fa-check"></i><b>5.2</b> Dynamics around the equilibria — stability</a><ul>
<li class="chapter" data-level="5.2.1" data-path="DDgrowth.html"><a href="DDgrowth.html#analytical-linear-stability-analysis"><i class="fa fa-check"></i><b>5.2.1</b> Analytical linear stability analysis</a></li>
<li class="chapter" data-level="5.2.2" data-path="DDgrowth.html"><a href="DDgrowth.html#projection-with-numerical-integration"><i class="fa fa-check"></i><b>5.2.2</b> Projection with numerical integration</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="DDgrowth.html"><a href="DDgrowth.html#other-forms-of-density-dependent-growth"><i class="fa fa-check"></i><b>5.3</b> Other forms of density-dependent growth</a><ul>
<li class="chapter" data-level="5.3.1" data-path="DDgrowth.html"><a href="DDgrowth.html#effects-of-n-on-birth-and-death-rates"><i class="fa fa-check"></i><b>5.3.1</b> Effects of N on birth and death rates</a></li>
<li class="chapter" data-level="5.3.2" data-path="DDgrowth.html"><a href="DDgrowth.html#theta-logistic-growth"><i class="fa fa-check"></i><b>5.3.2</b> Theta-logistic growth</a></li>
<li class="chapter" data-level="5.3.3" data-path="DDgrowth.html"><a href="DDgrowth.html#allee-effect"><i class="fa fa-check"></i><b>5.3.3</b> Allee effect</a></li>
<li class="chapter" data-level="5.3.4" data-path="DDgrowth.html"><a href="DDgrowth.html#the-integral-of-logistic-growth"><i class="fa fa-check"></i><b>5.3.4</b> The integral of logistic growth</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="DDgrowth.html"><a href="DDgrowth.html#discrete-density-dependent-growth"><i class="fa fa-check"></i><b>5.4</b> Discrete Density-dependent Growth</a><ul>
<li class="chapter" data-level="5.4.1" data-path="DDgrowth.html"><a href="DDgrowth.html#effects-of-r_d"><i class="fa fa-check"></i><b>5.4.1</b> Effects of <span class="math inline">\(r_d\)</span></a></li>
<li class="chapter" data-level="5.4.2" data-path="DDgrowth.html"><a href="DDgrowth.html#bifurcations"><i class="fa fa-check"></i><b>5.4.2</b> Bifurcations</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="DDgrowth.html"><a href="DDgrowth.html#maximum-sustained-yield"><i class="fa fa-check"></i><b>5.5</b> Maximum Sustained Yield</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="meta.html"><a href="meta.html"><i class="fa fa-check"></i><b>6</b> Populations in Space</a><ul>
<li class="chapter" data-level="6.1" data-path="meta.html"><a href="meta.html#source-sink-dynamics"><i class="fa fa-check"></i><b>6.1</b> Source-sink Dynamics</a><ul>
<li class="chapter" data-level="6.1.1" data-path="meta.html"><a href="meta.html#complications-and-cases"><i class="fa fa-check"></i><b>6.1.1</b> Complications and cases</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="meta.html"><a href="meta.html#metapopulations"><i class="fa fa-check"></i><b>6.2</b> Metapopulations</a><ul>
<li class="chapter" data-level="6.2.1" data-path="meta.html"><a href="meta.html#the-classic-levins-model"><i class="fa fa-check"></i><b>6.2.1</b> The classic Levins model</a></li>
<li class="chapter" data-level="6.2.2" data-path="meta.html"><a href="meta.html#propagule-rain"><i class="fa fa-check"></i><b>6.2.2</b> Propagule rain</a></li>
<li class="chapter" data-level="6.2.3" data-path="meta.html"><a href="meta.html#the-rescue-effect-and-the-core-satellite-model"><i class="fa fa-check"></i><b>6.2.3</b> The rescue effect and the core-satellite model</a></li>
<li class="chapter" data-level="6.2.4" data-path="meta.html"><a href="meta.html#parallels-with-logistic-growth"><i class="fa fa-check"></i><b>6.2.4</b> Parallels with Logistic Growth</a></li>
<li class="chapter" data-level="6.2.5" data-path="meta.html"><a href="meta.html#levins-vs.-hanski"><i class="fa fa-check"></i><b>6.2.5</b> Levins <span class="math inline">\(vs\)</span>. Hanski</a></li>
<li class="chapter" data-level="6.2.6" data-path="meta.html"><a href="meta.html#habitat-destruction"><i class="fa fa-check"></i><b>6.2.6</b> Habitat Destruction</a></li>
<li class="chapter" data-level="6.2.7" data-path="meta.html"><a href="meta.html#illustrating-the-effects-of-habitat-destruction"><i class="fa fa-check"></i><b>6.2.7</b> Illustrating the effects of habitat destruction</a></li>
<li class="chapter" data-level="6.2.8" data-path="meta.html"><a href="meta.html#different-assumptions-lead-to-different-predictions-about-rates-of-extinction"><i class="fa fa-check"></i><b>6.2.8</b> Different assumptions lead to different predictions about rates of extinction</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="meta.html"><a href="meta.html#hanskis-incidence-function"><i class="fa fa-check"></i><b>6.3</b> Hanski’s incidence function</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="competition.html"><a href="competition.html"><i class="fa fa-check"></i><b>7</b> Competition</a><ul>
<li class="chapter" data-level="7.1" data-path="competition.html"><a href="competition.html#lotka-volterra-interspecific-competition"><i class="fa fa-check"></i><b>7.1</b> Lotka-Volterra Interspecific Competition</a></li>
<li class="chapter" data-level="7.2" data-path="competition.html"><a href="competition.html#equilbria"><i class="fa fa-check"></i><b>7.2</b> Equilbria</a><ul>
<li class="chapter" data-level="7.2.1" data-path="competition.html"><a href="competition.html#isoclines"><i class="fa fa-check"></i><b>7.2.1</b> Isoclines</a></li>
<li class="chapter" data-level="7.2.2" data-path="competition.html"><a href="competition.html#finding-equilibria"><i class="fa fa-check"></i><b>7.2.2</b> Finding equilibria</a></li>
<li class="chapter" data-level="7.2.3" data-path="competition.html"><a href="competition.html#coexistence-the-invasion-criterion"><i class="fa fa-check"></i><b>7.2.3</b> Coexistence — the invasion criterion</a></li>
<li class="chapter" data-level="7.2.4" data-path="competition.html"><a href="competition.html#other-equilibria"><i class="fa fa-check"></i><b>7.2.4</b> Other equilibria</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="competition.html"><a href="competition.html#dynamics-at-the-equilibria"><i class="fa fa-check"></i><b>7.3</b> Dynamics at the Equilibria</a><ul>
<li class="chapter" data-level="7.3.1" data-path="competition.html"><a href="competition.html#determine-the-equilibria"><i class="fa fa-check"></i><b>7.3.1</b> Determine the equilibria</a></li>
<li class="chapter" data-level="7.3.2" data-path="competition.html"><a href="competition.html#create-the-jacobian-matrix"><i class="fa fa-check"></i><b>7.3.2</b> Create the Jacobian matrix</a></li>
<li class="chapter" data-level="7.3.3" data-path="competition.html"><a href="competition.html#solve-the-jacobian-at-an-equilibrium"><i class="fa fa-check"></i><b>7.3.3</b> Solve the Jacobian at an equilibrium</a></li>
<li class="chapter" data-level="7.3.4" data-path="competition.html"><a href="competition.html#use-the-jacobian-matrix"><i class="fa fa-check"></i><b>7.3.4</b> Use the Jacobian matrix</a></li>
<li class="chapter" data-level="7.3.5" data-path="competition.html"><a href="competition.html#three-interesting-equilbria"><i class="fa fa-check"></i><b>7.3.5</b> Three interesting equilbria</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="competition.html"><a href="competition.html#return-time-and-the-effect-of-r"><i class="fa fa-check"></i><b>7.4</b> Return Time and the Effect of <span class="math inline">\(r\)</span></a></li>
<li class="chapter" data-level="7.5" data-path="competition.html"><a href="competition.html#indirect-competition-for-resources"><i class="fa fa-check"></i><b>7.5</b> Indirect competition for resources</a><ul>
<li class="chapter" data-level="7.5.1" data-path="competition.html"><a href="competition.html#linear-and-nonlinear-responses"><i class="fa fa-check"></i><b>7.5.1</b> Linear and nonlinear responses</a></li>
<li class="chapter" data-level="7.5.2" data-path="competition.html"><a href="competition.html#relative-nonlinearity"><i class="fa fa-check"></i><b>7.5.2</b> Relative nonlinearity</a></li>
<li class="chapter" data-level="7.5.3" data-path="competition.html"><a href="competition.html#competition-for-two-resources-the-resource-ratio-model"><i class="fa fa-check"></i><b>7.5.3</b> Competition for two resources: the resource ratio model</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="competition.html"><a href="competition.html#summary"><i class="fa fa-check"></i><b>7.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="mutualisms.html"><a href="mutualisms.html"><i class="fa fa-check"></i><b>8</b> Mutualisms</a><ul>
<li class="chapter" data-level="8.1" data-path="mutualisms.html"><a href="mutualisms.html#background"><i class="fa fa-check"></i><b>8.1</b> Background</a></li>
<li class="chapter" data-level="8.2" data-path="mutualisms.html"><a href="mutualisms.html#lotka-volterra-mutualism"><i class="fa fa-check"></i><b>8.2</b> Lotka-Volterra mutualism</a></li>
<li class="chapter" data-level="8.3" data-path="mutualisms.html"><a href="mutualisms.html#consumer-resource-mutualism"><i class="fa fa-check"></i><b>8.3</b> Consumer-resource mutualism</a><ul>
<li class="chapter" data-level="8.3.1" data-path="mutualisms.html"><a href="mutualisms.html#a-model-of-uni-directional-mutualism"><i class="fa fa-check"></i><b>8.3.1</b> A model of uni-directional mutualism</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="mutualisms.html"><a href="mutualisms.html#plant-soil-feedbacks"><i class="fa fa-check"></i><b>8.4</b> Plant-soil feedbacks</a></li>
<li class="chapter" data-level="8.5" data-path="mutualisms.html"><a href="mutualisms.html#simulations-for-learning"><i class="fa fa-check"></i><b>8.5</b> Simulations for learning</a><ul>
<li class="chapter" data-level="8.5.1" data-path="mutualisms.html"><a href="mutualisms.html#lvg"><i class="fa fa-check"></i><b>8.5.1</b> <code>lvg()</code></a></li>
<li class="chapter" data-level="8.5.2" data-path="mutualisms.html"><a href="mutualisms.html#systematic-simulations"><i class="fa fa-check"></i><b>8.5.2</b> Systematic simulations</a></li>
<li class="chapter" data-level="8.5.3" data-path="mutualisms.html"><a href="mutualisms.html#checking-simulation-results"><i class="fa fa-check"></i><b>8.5.3</b> Checking simulation results</a></li>
<li class="chapter" data-level="8.5.4" data-path="mutualisms.html"><a href="mutualisms.html#comparing-simulation-results-to-analytical-solutions"><i class="fa fa-check"></i><b>8.5.4</b> Comparing simulation results to analytical solutions</a></li>
<li class="chapter" data-level="8.5.5" data-path="mutualisms.html"><a href="mutualisms.html#one-last-thing-using-the-jacobian-matrix"><i class="fa fa-check"></i><b>8.5.5</b> One last thing: using the Jacobian matrix</a></li>
<li class="chapter" data-level="8.5.6" data-path="mutualisms.html"><a href="mutualisms.html#in-fine"><i class="fa fa-check"></i><b>8.5.6</b> <em>In Fine</em></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="consumer-resource-interactions.html"><a href="consumer-resource-interactions.html"><i class="fa fa-check"></i><b>9</b> Consumer-resource Interactions</a><ul>
<li class="chapter" data-level="9.1" data-path="consumer-resource-interactions.html"><a href="consumer-resource-interactions.html#ratio-dependence"><i class="fa fa-check"></i><b>9.1</b> Ratio dependence</a><ul>
<li class="chapter" data-level="9.1.1" data-path="consumer-resource-interactions.html"><a href="consumer-resource-interactions.html#dynamics-of-ratio-dependent-predation"><i class="fa fa-check"></i><b>9.1.1</b> Dynamics of ratio dependent predation</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="consumer-resource-interactions.html"><a href="consumer-resource-interactions.html#prey-dependence"><i class="fa fa-check"></i><b>9.2</b> Prey dependence</a><ul>
<li class="chapter" data-level="9.2.1" data-path="consumer-resource-interactions.html"><a href="consumer-resource-interactions.html#dyanmics-of-prey-dependent-predation"><i class="fa fa-check"></i><b>9.2.1</b> Dyanmics of prey-dependent predation</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="consumer-resource-interactions.html"><a href="consumer-resource-interactions.html#interlude-functional-response---what-an-individual-predator-does"><i class="fa fa-check"></i><b>9.3</b> Interlude: Functional response - what an individual predator does</a></li>
<li class="chapter" data-level="9.4" data-path="consumer-resource-interactions.html"><a href="consumer-resource-interactions.html#stability-analysis-for-the-prey-dependent-lotkavolterra-model"><i class="fa fa-check"></i><b>9.4</b> Stability analysis for the prey-dependent Lotka–Volterra model</a></li>
<li class="chapter" data-level="9.5" data-path="consumer-resource-interactions.html"><a href="consumer-resource-interactions.html#prey-carrying-capacity-and-type-ii-functional-response"><i class="fa fa-check"></i><b>9.5</b> Prey carrying capacity and type II functional response</a><ul>
<li class="chapter" data-level="9.5.1" data-path="consumer-resource-interactions.html"><a href="consumer-resource-interactions.html#paradox-of-enrichment"><i class="fa fa-check"></i><b>9.5.1</b> Paradox of enrichment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="host-parasitoid-relations.html"><a href="host-parasitoid-relations.html"><i class="fa fa-check"></i><b>10</b> Host-parasitoid relations</a><ul>
<li class="chapter" data-level="10.1" data-path="host-parasitoid-relations.html"><a href="host-parasitoid-relations.html#independent-and-random-attacks"><i class="fa fa-check"></i><b>10.1</b> Independent and random attacks</a><ul>
<li class="chapter" data-level="10.1.1" data-path="host-parasitoid-relations.html"><a href="host-parasitoid-relations.html#simulating-simple-host-parasitoid-dynamics"><i class="fa fa-check"></i><b>10.1.1</b> Simulating simple host-parasitoid dynamics</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="host-parasitoid-relations.html"><a href="host-parasitoid-relations.html#aggregation-leads-to-coexistence"><i class="fa fa-check"></i><b>10.2</b> Aggregation leads to coexistence</a><ul>
<li class="chapter" data-level="10.2.1" data-path="host-parasitoid-relations.html"><a href="host-parasitoid-relations.html#equilibria-for-a-discrete-time-model"><i class="fa fa-check"></i><b>10.2.1</b> Equilibria for a discrete-time model</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="host-parasitoid-relations.html"><a href="host-parasitoid-relations.html#stability-of-hostparasitoid-dynamics"><i class="fa fa-check"></i><b>10.3</b> Stability of host–parasitoid dynamics</a></li>
<li class="chapter" data-level="10.4" data-path="mutualisms.html"><a href="mutualisms.html#in-fine"><i class="fa fa-check"></i><b>10.4</b> <em>In Fine</em></a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="disease.html"><a href="disease.html"><i class="fa fa-check"></i><b>11</b> Disease</a><ul>
<li class="chapter" data-level="11.1" data-path="disease.html"><a href="disease.html#closed-epidemics"><i class="fa fa-check"></i><b>11.1</b> Closed epidemics</a><ul>
<li class="chapter" data-level="11.1.1" data-path="disease.html"><a href="disease.html#density-dependent-transmission"><i class="fa fa-check"></i><b>11.1.1</b> Density-dependent transmission</a></li>
<li class="chapter" data-level="11.1.2" data-path="disease.html"><a href="disease.html#frequency-dependent-transmission"><i class="fa fa-check"></i><b>11.1.2</b> Frequency-dependent transmission</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="disease.html"><a href="disease.html#open-epidemics"><i class="fa fa-check"></i><b>11.2</b> Open epidemics</a></li>
<li class="chapter" data-level="11.3" data-path="disease.html"><a href="disease.html#modeling-data-from-bombay"><i class="fa fa-check"></i><b>11.3</b> Modeling data from Bombay</a><ul>
<li class="chapter" data-level="11.3.1" data-path="disease.html"><a href="disease.html#optimization"><i class="fa fa-check"></i><b>11.3.1</b> Optimization</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="food-webs-and-other-networks.html"><a href="food-webs-and-other-networks.html"><i class="fa fa-check"></i><b>12</b> Food webs and other networks</a><ul>
<li class="chapter" data-level="12.1" data-path="food-webs-and-other-networks.html"><a href="food-webs-and-other-networks.html#food-web-characteristics"><i class="fa fa-check"></i><b>12.1</b> Food Web Characteristics</a></li>
<li class="chapter" data-level="12.2" data-path="food-webs-and-other-networks.html"><a href="food-webs-and-other-networks.html#does-omnivory-destablize-food-chains"><i class="fa fa-check"></i><b>12.2</b> Does omnivory destablize food chains?</a><ul>
<li class="chapter" data-level="12.2.1" data-path="food-webs-and-other-networks.html"><a href="food-webs-and-other-networks.html#multi-species-lotkavolterra-notation"><i class="fa fa-check"></i><b>12.2.1</b> Multi-species Lotka–Volterra notation</a></li>
<li class="chapter" data-level="12.2.2" data-path="mutualisms.html"><a href="mutualisms.html#background"><i class="fa fa-check"></i><b>12.2.2</b> Background</a></li>
<li class="chapter" data-level="12.2.3" data-path="food-webs-and-other-networks.html"><a href="food-webs-and-other-networks.html#implementing-pimm-and-lawtons-methods"><i class="fa fa-check"></i><b>12.2.3</b> Implementing Pimm and Lawton’s Methods</a></li>
<li class="chapter" data-level="12.2.4" data-path="food-webs-and-other-networks.html"><a href="food-webs-and-other-networks.html#shortening-the-chain"><i class="fa fa-check"></i><b>12.2.4</b> Shortening the Chain</a></li>
<li class="chapter" data-level="12.2.5" data-path="food-webs-and-other-networks.html"><a href="food-webs-and-other-networks.html#adding-omnivory"><i class="fa fa-check"></i><b>12.2.5</b> Adding Omnivory</a></li>
<li class="chapter" data-level="12.2.6" data-path="food-webs-and-other-networks.html"><a href="food-webs-and-other-networks.html#comparing-chain-a-versus-b"><i class="fa fa-check"></i><b>12.2.6</b> Comparing Chain A versus B</a></li>
<li class="chapter" data-level="12.2.7" data-path="food-webs-and-other-networks.html"><a href="food-webs-and-other-networks.html#re-evaluating-take-home-messages"><i class="fa fa-check"></i><b>12.2.7</b> Re-evaluating Take-Home Messages</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="food-webs-and-other-networks.html"><a href="food-webs-and-other-networks.html#perhaps-mutualism-stabilizes-bipartite-networks"><i class="fa fa-check"></i><b>12.3</b> Perhaps mutualism stabilizes bipartite networks</a><ul>
<li class="chapter" data-level="12.3.1" data-path="food-webs-and-other-networks.html"><a href="food-webs-and-other-networks.html#creating-bipartite-webs"><i class="fa fa-check"></i><b>12.3.1</b> Creating bipartite webs</a></li>
<li class="chapter" data-level="12.3.2" data-path="food-webs-and-other-networks.html"><a href="food-webs-and-other-networks.html#testing-effects-of-nestedness-and-modularity-on-network-resilience."><i class="fa fa-check"></i><b>12.3.2</b> Testing effects of nestedness and modularity on network resilience.</a></li>
<li class="chapter" data-level="12.3.3" data-path="food-webs-and-other-networks.html"><a href="food-webs-and-other-networks.html#path-analysis"><i class="fa fa-check"></i><b>12.3.3</b> Path Analysis</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="food-webs-and-other-networks.html"><a href="food-webs-and-other-networks.html#exploring-pandora-right-here-at-home"><i class="fa fa-check"></i><b>12.4</b> Exploring Pandora, right here at home</a><ul>
<li class="chapter" data-level="12.4.1" data-path="food-webs-and-other-networks.html"><a href="food-webs-and-other-networks.html#properties-assessed"><i class="fa fa-check"></i><b>12.4.1</b> Properties assessed</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="diversity.html"><a href="diversity.html"><i class="fa fa-check"></i><b>13</b> Diversity</a><ul>
<li class="chapter" data-level="13.1" data-path="mutualisms.html"><a href="mutualisms.html#background"><i class="fa fa-check"></i><b>13.1</b> Background</a></li>
<li class="chapter" data-level="13.2" data-path="diversity.html"><a href="diversity.html#species-composition"><i class="fa fa-check"></i><b>13.2</b> Species Composition</a><ul>
<li class="chapter" data-level="13.2.1" data-path="diversity.html"><a href="diversity.html#measures-of-abundance"><i class="fa fa-check"></i><b>13.2.1</b> Measures of abundance</a></li>
<li class="chapter" data-level="13.2.2" data-path="diversity.html"><a href="diversity.html#dissimilarities-and-distances"><i class="fa fa-check"></i><b>13.2.2</b> Dissimilarities and Distances</a></li>
<li class="chapter" data-level="13.2.3" data-path="diversity.html"><a href="diversity.html#displaying-multidimensional-distances"><i class="fa fa-check"></i><b>13.2.3</b> Displaying multidimensional distances</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="diversity.html"><a href="diversity.html#diversity-1"><i class="fa fa-check"></i><b>13.3</b> Diversity</a></li>
<li class="chapter" data-level="13.4" data-path="diversity.html"><a href="diversity.html#species-diversity"><i class="fa fa-check"></i><b>13.4</b> Species diversity</a></li>
<li class="chapter" data-level="13.5" data-path="diversity.html"><a href="diversity.html#rarefaction-and-total-species-richness"><i class="fa fa-check"></i><b>13.5</b> Rarefaction and total species richness</a><ul>
<li class="chapter" data-level="13.5.1" data-path="diversity.html"><a href="diversity.html#an-example-of-rarefaction-and-total-species-richness"><i class="fa fa-check"></i><b>13.5.1</b> An example of rarefaction and total species richness</a></li>
</ul></li>
<li class="chapter" data-level="13.6" data-path="diversity.html"><a href="diversity.html#distributions"><i class="fa fa-check"></i><b>13.6</b> Distributions</a><ul>
<li class="chapter" data-level="13.6.1" data-path="diversity.html"><a href="diversity.html#log-normal-distribution"><i class="fa fa-check"></i><b>13.6.1</b> Log-normal distribution</a></li>
<li class="chapter" data-level="13.6.2" data-path="diversity.html"><a href="diversity.html#other-distributions"><i class="fa fa-check"></i><b>13.6.2</b> Other distributions</a></li>
<li class="chapter" data-level="13.6.3" data-path="diversity.html"><a href="diversity.html#pattern-vs.-process"><i class="fa fa-check"></i><b>13.6.3</b> Pattern <em>vs.</em> process</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="diversity.html"><a href="diversity.html#neutral-theory-of-biodiversity-and-biogeography"><i class="fa fa-check"></i><b>13.7</b> Neutral Theory of Biodiversity and Biogeography</a><ul>
<li class="chapter" data-level="13.7.1" data-path="diversity.html"><a href="diversity.html#different-flavors-of-neutral-communities"><i class="fa fa-check"></i><b>13.7.1</b> Different flavors of neutral communities</a></li>
<li class="chapter" data-level="13.7.2" data-path="diversity.html"><a href="diversity.html#investigating-neutral-communities"><i class="fa fa-check"></i><b>13.7.2</b> Investigating neutral communities</a></li>
</ul></li>
<li class="chapter" data-level="13.8" data-path="diversity.html"><a href="diversity.html#speciesarea-relations"><i class="fa fa-check"></i><b>13.8</b> Species–area relations</a><ul>
<li class="chapter" data-level="13.8.1" data-path="diversity.html"><a href="diversity.html#island-biogeography"><i class="fa fa-check"></i><b>13.8.1</b> Island biogeography</a></li>
</ul></li>
<li class="chapter" data-level="13.9" data-path="diversity.html"><a href="diversity.html#diversity-partitioning"><i class="fa fa-check"></i><b>13.9</b> Diversity Partitioning</a><ul>
<li class="chapter" data-level="13.9.1" data-path="diversity.html"><a href="diversity.html#partitioning-speciesarea-relations"><i class="fa fa-check"></i><b>13.9.1</b> Partitioning species–area relations</a></li>
</ul></li>
<li class="chapter" data-level="13.10" data-path="competition.html"><a href="competition.html#summary"><i class="fa fa-check"></i><b>13.10</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="appendix.html"><a href="appendix.html"><i class="fa fa-check"></i><b>14</b> Appendix</a><ul>
<li class="chapter" data-level="14.1" data-path="appendix.html"><a href="appendix.html#very-introductory-materials"><i class="fa fa-check"></i><b>14.1</b> Very introductory materials</a></li>
<li class="chapter" data-level="14.2" data-path="appendix.html"><a href="appendix.html#writing-your-own-functions"><i class="fa fa-check"></i><b>14.2</b> Writing your own functions</a></li>
<li class="chapter" data-level="14.3" data-path="appendix.html"><a href="appendix.html#iterated-actions-the-apply-family-and-loops"><i class="fa fa-check"></i><b>14.3</b> Iterated Actions: the <code>apply</code> Family and Loops</a><ul>
<li class="chapter" data-level="14.3.1" data-path="appendix.html"><a href="appendix.html#iterations-of-independent-actions"><i class="fa fa-check"></i><b>14.3.1</b> Iterations of independent actions</a></li>
<li class="chapter" data-level="14.3.2" data-path="appendix.html"><a href="appendix.html#dependent-iterations"><i class="fa fa-check"></i><b>14.3.2</b> Dependent iterations</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="appendix.html"><a href="appendix.html#probability-distributions-and-randomization"><i class="fa fa-check"></i><b>14.4</b> Probability Distributions and Randomization</a></li>
<li class="chapter" data-level="14.5" data-path="appendix.html"><a href="appendix.html#numerical-integration-of-ordinary-differential-equations"><i class="fa fa-check"></i><b>14.5</b> Numerical integration of ordinary differential equations</a></li>
<li class="chapter" data-level="14.6" data-path="DID.html"><a href="DID.html#eigenanalysis"><i class="fa fa-check"></i><b>14.6</b> Eigenanalysis</a><ul>
<li class="chapter" data-level="14.6.1" data-path="appendix.html"><a href="appendix.html#eigenanalysis-of-demographic-versus-jacobian-matrices"><i class="fa fa-check"></i><b>14.6.1</b> Eigenanalysis of demographic versus Jacobian matrices</a></li>
</ul></li>
<li class="chapter" data-level="14.7" data-path="appendix.html"><a href="appendix.html#derivation-of-the-right-eigenvalues"><i class="fa fa-check"></i><b>14.7</b> Derivation of the right eigenvalues</a></li>
<li class="chapter" data-level="14.8" data-path="appendix.html"><a href="appendix.html#symbols-used-in-this-book"><i class="fa fa-check"></i><b>14.8</b> Symbols used in this book</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>15</b> References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Primer of Ecology using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="appendix" class="section level1">
<h1><span class="header-section-number">14</span> Appendix</h1>
<div id="very-introductory-materials" class="section level2">
<h2><span class="header-section-number">14.1</span> Very introductory materials</h2>
<ul>
<li>About R: <a href="https://www.r-project.org/about.html" class="uri">https://www.r-project.org/about.html</a></li>
<li>Getting started on R, (R documentation): <a href="https://cran.r-project.org/doc/manuals/r-release/R-intro.html" class="uri">https://cran.r-project.org/doc/manuals/r-release/R-intro.html</a></li>
<li>Getting started on R interactively, using the RStudio interface: <a href="https://swirlstats.com/" class="uri">https://swirlstats.com/</a></li>
</ul>
<p>Here are two statistics texts, both of which have great introductory material on getting started with the R language.</p>
<ul>
<li><a href="http://users.miamioh.edu/fishert4/sta363/" class="uri">http://users.miamioh.edu/fishert4/sta363/</a> (a great statistics text)</li>
<li><a href="http://r-statistics.co/" class="uri">http://r-statistics.co/</a> (graphics and stats; has ads)</li>
</ul>
<p>Arranging and summarizing data with <code>dplyr</code>: <a href="https://cran.r-project.org/web/packages/dplyr/vignettes/dplyr.html" class="uri">https://cran.r-project.org/web/packages/dplyr/vignettes/dplyr.html</a></p>
<p><em>R is a language. Use it every day, and you will learn it quickly.</em></p>
</div>
<div id="writing-your-own-functions" class="section level2">
<h2><span class="header-section-number">14.2</span> Writing your own functions</h2>
<p>One very cool thing in R is that you can write your own functions. Indeed it is the extensibility of R that makes it the home of cutting edge working, because edge cutters (i.e., leading scientists) can write code that we all can use. People actually write entire <em>packages</em>, which are integrated collections of functions, and R has been extended with hundreds of such packages available for download at all the R mirrors.</p>
<p>Let’s make our own function to calculate a mean. Let’s further pretend you work for an unethical boss who wants you to show that average sales are higher than they really are. Therefore your function should provide a mean plus 5%.</p>
<div class="sourceCode" id="cb527"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb527-1"><a href="appendix.html#cb527-1"></a>MyBogusMean &lt;-<span class="st"> </span><span class="cf">function</span>(x, <span class="dt">cheat=</span><span class="fl">0.05</span>) { SumOfX &lt;-<span class="st"> </span><span class="kw">sum</span>(x)</span>
<span id="cb527-2"><a href="appendix.html#cb527-2"></a>                             n &lt;-<span class="st"> </span><span class="kw">length</span>(x)</span>
<span id="cb527-3"><a href="appendix.html#cb527-3"></a>                             trueMean &lt;-<span class="st"> </span>SumOfX<span class="op">/</span>n </span>
<span id="cb527-4"><a href="appendix.html#cb527-4"></a>                           (<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>cheat) <span class="op">*</span><span class="st"> </span>trueMean}</span>
<span id="cb527-5"><a href="appendix.html#cb527-5"></a>RealSales &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">100</span>, <span class="dv">200</span>, <span class="dv">300</span>)</span>
<span id="cb527-6"><a href="appendix.html#cb527-6"></a><span class="kw">MyBogusMean</span>(RealSales)</span></code></pre></div>
<pre><code>## [1] 210</code></pre>
<p>Thus a function can take any input, do stuff, including produce graphics, or interact with the operating system, or manipulated numbers. You decide on the arguments of the function, in this case, <code>x</code> and <code>cheat</code>. Note that we supplied a number for <code>cheat</code>; this results in the <code>cheat</code> argument having a <em>default</em> value, and we do not have to supply it. If an argument does not have a default, we have to supply it. If there is a default value, we can change it. Now try these.</p>
<div class="sourceCode" id="cb529"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb529-1"><a href="appendix.html#cb529-1"></a><span class="kw">MyBogusMean</span>(RealSales, <span class="dt">cheat=</span><span class="fl">0.1</span>)</span></code></pre></div>
<pre><code>## [1] 220</code></pre>
<div class="sourceCode" id="cb531"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb531-1"><a href="appendix.html#cb531-1"></a><span class="kw">MyBogusMean</span>(RealSales, <span class="dt">cheat=</span><span class="dv">0</span>)</span></code></pre></div>
<pre><code>## [1] 200</code></pre>
</div>
<div id="iterated-actions-the-apply-family-and-loops" class="section level2">
<h2><span class="header-section-number">14.3</span> Iterated Actions: the <code>apply</code> Family and Loops</h2>
<p>We often want to perform an action again and again and again…, perhaps thousands or millions of times. In some cases, each action is independent — we just want to do it a lot. In these cases, we have a choice of methods. Other times, each action depends on the previous action. In this case, I always use for-loops.<a href="#fn81" class="footnote-ref" id="fnref81"><sup>81</sup></a> Here I discuss first methods that work only for independent actions.</p>
<div id="iterations-of-independent-actions" class="section level3">
<h3><span class="header-section-number">14.3.1</span> Iterations of independent actions</h3>
<p>Imagine that we have a matrix or data frame and we want to do the same thing to each column (or row). For this we use apply, to “apply” a function to each column (or row). We tell <code>apply</code> what data we want to use, we tell it the “margin” we want to focus on, and then we tell it the function. The <em>margin</em> is the <em>side</em> of the matrix. We describe matrices by their number of rows, then columns, as in “a 2 by 5 matrix,” so rows constitute the first margin, and columns constitute the second margin. Here we create a <span class="math inline">\(2 \times 5\)</span> matrix, and take the mean of rows, for the first margin. Then we sum the columns for the second margin.</p>
<div class="sourceCode" id="cb533"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb533-1"><a href="appendix.html#cb533-1"></a>m &lt;-<span class="st"> </span><span class="kw">matrix</span>( <span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, <span class="dt">nrow=</span><span class="dv">2</span>)</span>
<span id="cb533-2"><a href="appendix.html#cb533-2"></a>m</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4] [,5]
## [1,]    1    3    5    7    9
## [2,]    2    4    6    8   10</code></pre>
<div class="sourceCode" id="cb535"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb535-1"><a href="appendix.html#cb535-1"></a><span class="kw">apply</span>(m, <span class="dt">MARGIN=</span><span class="dv">1</span>, mean)</span></code></pre></div>
<pre><code>## [1] 5 6</code></pre>
<div class="sourceCode" id="cb537"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb537-1"><a href="appendix.html#cb537-1"></a><span class="kw">apply</span>(m, <span class="dt">MARGIN=</span><span class="dv">2</span>, sum)</span></code></pre></div>
<pre><code>## [1]  3  7 11 15 19</code></pre>
<p>See <code>?rowMeans</code> for simple, and even faster, operations.</p>
<p>Similarly, <code>lapply</code> will “apply” a function to each element of a list, or each column of a data frame, and always returns a list. The function <code>sapply</code> does something similar, but will simplify the result, to a less complex data structure if possible.</p>
<p>Here we do an independent operation 10 times using <code>sapply</code>, defining a function on-the-fly to calculate the mean of a random draw of five observations from the standard normal distribution.</p>
<div class="sourceCode" id="cb539"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb539-1"><a href="appendix.html#cb539-1"></a><span class="kw">sapply</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, <span class="cf">function</span>(i) <span class="kw">mean</span>( <span class="kw">rnorm</span>(<span class="dv">5</span>) ) )</span></code></pre></div>
<pre><code>##  [1]  0.5213739  0.3873709  0.1664762  0.2280835  0.1689191 -0.5540140
##  [7]  0.2087952  0.4849436 -0.4930031 -0.2168586</code></pre>
</div>
<div id="dependent-iterations" class="section level3">
<h3><span class="header-section-number">14.3.2</span> Dependent iterations</h3>
<p>Often the repeated actions depend on previous outcomes, as with
population growth. Here we provide a couple of examples where we accomplish this with <em>for loops</em>.</p>
<p>One thing to keep in mind for <em>for loops</em> in R is that the computation of this is fastest if we first make a holder for the output. Here I simulate a random walk, where, for instance, we start with 25 individuals at time = 0, and increase or decrease by some amount that is drawn randomly from a normal distribution, with a mean of zero and a standard deviation 2. We will round the “amount” to the nearest integer (the zero-th decimal place). Your output will differ because it is a random process.</p>
<div class="sourceCode" id="cb541"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb541-1"><a href="appendix.html#cb541-1"></a>gens &lt;-<span class="st"> </span><span class="dv">10</span></span>
<span id="cb541-2"><a href="appendix.html#cb541-2"></a>output &lt;-<span class="st"> </span><span class="kw">numeric</span>(gens <span class="op">+</span><span class="st"> </span><span class="dv">1</span>)</span>
<span id="cb541-3"><a href="appendix.html#cb541-3"></a>output[<span class="dv">1</span>] &lt;-<span class="st"> </span><span class="dv">25</span></span>
<span id="cb541-4"><a href="appendix.html#cb541-4"></a><span class="cf">for</span>( t <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>gens ) output[t <span class="op">+</span><span class="st"> </span><span class="dv">1</span>] &lt;-<span class="st"> </span>output[t] <span class="op">+</span><span class="st"> </span><span class="kw">round</span>( <span class="kw">rnorm</span>(<span class="dt">n=</span><span class="dv">1</span>, <span class="dt">mean=</span><span class="dv">0</span>, <span class="dt">sd=</span><span class="dv">2</span>), <span class="dv">0</span>)</span>
<span id="cb541-5"><a href="appendix.html#cb541-5"></a>output</span></code></pre></div>
<pre><code>##  [1] 25 23 20 19 17 17 17 16 17 17 17</code></pre>
</div>
</div>
<div id="probability-distributions-and-randomization" class="section level2">
<h2><span class="header-section-number">14.4</span> Probability Distributions and Randomization</h2>
<p>R has a variety of probability distributions built-in. For the normal distribution, for instance, there are four functions.</p>
<ul>
<li><code>dnorm</code> The probability density function, that creates the widely observed bell-shaped curve.</li>
<li><code>pnorm</code> The cumulative probability function that we usually use to describe the probability that a test statistic is greater than or equal to a critical value.</li>
<li><code>qnorm</code> The quantile function that takes probabilities as input.</li>
<li><code>rnorm</code> A random number generator which draws values (quantiles) from a distribution with a specified mean and standard deviation.</li>
</ul>
<p>For each of these, default parameter values return the standard normal distribution (<span class="math inline">\(\mu=0\)</span>, <span class="math inline">\(Sigma=1\)</span>), but these parameters can be changed.</p>
<p>Here we have the 95% confidence intervals.</p>
<div class="sourceCode" id="cb543"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb543-1"><a href="appendix.html#cb543-1"></a><span class="kw">qnorm</span>(<span class="dt">p=</span><span class="kw">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))</span></code></pre></div>
<pre><code>## [1] -1.959964  1.959964</code></pre>
<p>Next we create a histogram using 20 random draws from a normal
distribution with a mean of 11 and a standard deviation of 6; we overlay this with the probability density function (Fig. <a href="appendix.html#fig:myhist">14.1</a>).</p>
<div class="sourceCode" id="cb545"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb545-1"><a href="appendix.html#cb545-1"></a>myplot &lt;-<span class="st"> </span><span class="kw">hist</span>(<span class="kw">rnorm</span>(<span class="dv">20</span>, <span class="dt">m=</span><span class="dv">11</span>, <span class="dt">sd=</span><span class="dv">6</span>), <span class="dt">probability=</span><span class="ot">TRUE</span>)</span>
<span id="cb545-2"><a href="appendix.html#cb545-2"></a>myplot</span>
<span id="cb545-3"><a href="appendix.html#cb545-3"></a><span class="kw">lines</span>(myplot<span class="op">$</span>mids, <span class="kw">dnorm</span>(myplot<span class="op">$</span>mids, <span class="dt">m=</span><span class="dv">11</span>, <span class="dt">sd=</span><span class="dv">6</span>) )</span></code></pre></div>
<div class="figure"><span id="fig:myhist"></span>
<img src="figs/myhist-1.png" alt="*Histogram of random numbers drawn from a normal distribution with $\mu=11$ and $\sigma=6$. The normal probability density function is drawn as well.*" width="90%" />
<p class="caption">
Figure 14.1: <em>Histogram of random numbers drawn from a normal distribution with <span class="math inline">\(\mu=11\)</span> and <span class="math inline">\(\sigma=6\)</span>. The normal probability density function is drawn as well.</em>
</p>
</div>
</div>
<div id="numerical-integration-of-ordinary-differential-equations" class="section level2">
<h2><span class="header-section-number">14.5</span> Numerical integration of ordinary differential equations</h2>
<p>In order to study continuous population dynamics, we often would like to integrate complex nonlinear functions of population dynamics. To do this, we need to use numerical techniques that turn the infinitely small steps of calculus, <span class="math inline">\(\d x\)</span>, into very small, but finite steps, in order to approximate the change in <span class="math inline">\(y\)</span>, given the change in <span class="math inline">\(x\)</span>, or <span class="math inline">\(dy/dx\)</span>. Mathematicians and computer scientists have devised very clever ways of doing this very accurately and precisely. In R, the best package for this is <code>deSolve</code>, which contains several <em>solvers</em> for differential equations that perform numerical integration. We will access these solvers (i.e. numerical integraters) using the <code>ode</code> function in the <code>deSolve</code> package. This function, <code>ode</code>, is a “wrapper” for the underlying suite of functions that do the work. That is, it provides a simple way to use any one of the small suite of functions.</p>
<p>When we have an ordinary differential equation (ODE) such as logistic growth, <span class="math inline">\(dN/dt = rN(1-\alpha N)\)</span>, we say that we “solve” the equation for a particular time interval given a set of parameters and initial conditions or initial population size. For instance, we say that we solve the logistic growth model for time at <span class="math inline">\(t=0,\, 1 \ldots \, 20\)</span>, with parameters <span class="math inline">\(r=1\)</span>, <span class="math inline">\(\alpha=0.001\)</span>, and <span class="math inline">\(N_0=10\)</span>.</p>
<p>Let’s do an example with <code>ode</code>, using logistic growth. We first have to define a function in a particular way. The arguments for the function must be time, a vector of populations, and a vector or list of model parameters.</p>
<div class="sourceCode" id="cb546"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb546-1"><a href="appendix.html#cb546-1"></a>logGrowth &lt;-<span class="st"> </span><span class="cf">function</span>(t, y, p){</span>
<span id="cb546-2"><a href="appendix.html#cb546-2"></a>  N &lt;-<span class="st"> </span>y[<span class="dv">1</span>]</span>
<span id="cb546-3"><a href="appendix.html#cb546-3"></a>  <span class="kw">with</span>(<span class="kw">as.list</span>(p), {</span>
<span id="cb546-4"><a href="appendix.html#cb546-4"></a>    dN.dt &lt;-<span class="st"> </span>r <span class="op">*</span><span class="st"> </span>N <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>a <span class="op">*</span><span class="st"> </span>N)</span>
<span id="cb546-5"><a href="appendix.html#cb546-5"></a>    <span class="kw">return</span>( <span class="kw">list</span>( dN.dt ) )</span>
<span id="cb546-6"><a href="appendix.html#cb546-6"></a>  } )</span>
<span id="cb546-7"><a href="appendix.html#cb546-7"></a>}</span></code></pre></div>
<p>Note that I like to convert <span class="math inline">\(y\)</span> into a readable or transparent state variable (<span class="math inline">\(N\)</span> in this case). I also like to use <code>with</code> which allows me to use the names of my parameters <span class="citation">(Petzoldt <a href="#ref-Petzoldt:2003dp" role="doc-biblioref">2003</a>)</span>; this works only is <code>p</code> is a vector with named paramters (see below). Finally, we return the derivative as a list of one component.</p>
<p>The following is equivalent, but slightly less readable or transparent.</p>
<div class="sourceCode" id="cb547"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb547-1"><a href="appendix.html#cb547-1"></a>  logGrowth &lt;-<span class="st"> </span><span class="cf">function</span>(t, y, p){</span>
<span id="cb547-2"><a href="appendix.html#cb547-2"></a>    dN.dt &lt;-<span class="st"> </span>p[<span class="dv">1</span>] <span class="op">*</span><span class="st"> </span>y[<span class="dv">1</span>] <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>p[<span class="dv">2</span>] <span class="op">*</span><span class="st"> </span>y[<span class="dv">1</span>])</span>
<span id="cb547-3"><a href="appendix.html#cb547-3"></a>    <span class="kw">return</span>( <span class="kw">list</span>( dN.dt ) )</span>
<span id="cb547-4"><a href="appendix.html#cb547-4"></a>  }</span></code></pre></div>
<p>This requires that the order of the parameters is expected, that <span class="math inline">\(r\)</span> is first and <span class="math inline">\(\alpha\)</span> is second.</p>
<p>To solve the ODE, we will need to specify parameters, and initial conditions. Because we are using a vector of named parameters, we need to make sure we name them! We also need to supply the time steps we want.</p>
<div class="sourceCode" id="cb548"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb548-1"><a href="appendix.html#cb548-1"></a>p &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dt">r=</span><span class="dv">1</span>, <span class="dt">a =</span> <span class="fl">0.001</span>)</span>
<span id="cb548-2"><a href="appendix.html#cb548-2"></a>y0 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dt">N=</span><span class="dv">10</span>)</span>
<span id="cb548-3"><a href="appendix.html#cb548-3"></a>t &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">20</span></span></code></pre></div>
<p>Now you put it all into <code>ode</code>, with the correct arguments. The output is a matrix, with the first column being the time steps, and the remaining being your state variables. First we load the <code>deSolve</code> package.</p>
<div class="sourceCode" id="cb549"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb549-1"><a href="appendix.html#cb549-1"></a><span class="kw">library</span>(deSolve)</span>
<span id="cb549-2"><a href="appendix.html#cb549-2"></a>out &lt;-<span class="st"> </span><span class="kw">ode</span>(<span class="dt">y=</span>y0, <span class="dt">times=</span>t, <span class="dt">func=</span>logGrowth, <span class="dt">parms=</span>p)</span>
<span id="cb549-3"><a href="appendix.html#cb549-3"></a>out[<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>,]</span></code></pre></div>
<pre><code>##      time         N
## [1,]    1  10.00000
## [2,]    2  26.72369
## [3,]    3  69.45310
## [4,]    4 168.66426
## [5,]    5 355.46079</code></pre>
<div class="sourceCode" id="cb551"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb551-1"><a href="appendix.html#cb551-1"></a><span class="kw">plot</span>(out)</span></code></pre></div>
<p><img src="figs/unnamed-chunk-260-1.png" width="90%" /></p>
<p>If you are going to model more than two species, y becomes a vector of length 2. Here we create a function for Lotka-Volterra competition, where
<span class="math display">\[\frac{d N_1}{d t} = r_1 N_1\left(1 - \alpha_{11} N_1 - \alpha_{12} N_2 \right)\]</span>
<span class="math display">\[\frac{d N_2}{d t} = r_2N_2\left(1 - \alpha_{22}N_2 - \alpha_{21}N_1 \right)\]</span></p>
<div class="sourceCode" id="cb552"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb552-1"><a href="appendix.html#cb552-1"></a>LVComp &lt;-<span class="st"> </span><span class="cf">function</span>(t, y, p){</span>
<span id="cb552-2"><a href="appendix.html#cb552-2"></a>  N &lt;-<span class="st"> </span>y</span>
<span id="cb552-3"><a href="appendix.html#cb552-3"></a>  <span class="kw">with</span>(<span class="kw">as.list</span>(p), {</span>
<span id="cb552-4"><a href="appendix.html#cb552-4"></a>    dN1.dt &lt;-<span class="st"> </span>r[<span class="dv">1</span>] <span class="op">*</span><span class="st"> </span>N[<span class="dv">1</span>] <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>a[<span class="dv">1</span>,<span class="dv">1</span>]<span class="op">*</span>N[<span class="dv">1</span>] <span class="op">-</span><span class="st"> </span>a[<span class="dv">1</span>,<span class="dv">2</span>]<span class="op">*</span>N[<span class="dv">2</span>])</span>
<span id="cb552-5"><a href="appendix.html#cb552-5"></a>    dN2.dt &lt;-<span class="st"> </span>r[<span class="dv">2</span>] <span class="op">*</span><span class="st"> </span>N[<span class="dv">2</span>] <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>a[<span class="dv">2</span>,<span class="dv">1</span>]<span class="op">*</span>N[<span class="dv">1</span>] <span class="op">-</span><span class="st"> </span>a[<span class="dv">2</span>,<span class="dv">2</span>]<span class="op">*</span>N[<span class="dv">2</span>])</span>
<span id="cb552-6"><a href="appendix.html#cb552-6"></a>    <span class="kw">return</span>( <span class="kw">list</span>( <span class="kw">c</span>(dN1.dt, dN2.dt) ) )</span>
<span id="cb552-7"><a href="appendix.html#cb552-7"></a>  } )</span>
<span id="cb552-8"><a href="appendix.html#cb552-8"></a>}</span></code></pre></div>
<p>Note that <code>LVComp</code> assumes that <span class="math inline">\(N\)</span> and <span class="math inline">\(r\)</span> are vectors, and the competition coefficients are in a matrix. For instance, the function extracts the the first element of <code>r</code> for the first species (<code>r[1]</code>); for the intraspecific competition coefficient for species 1, it uses the element of <code>a</code> that is in the first column and first row (<code>a[1,1]</code>). The vector of population sizes, <span class="math inline">\(N\)</span>, contains one value for each population <em>at one time point</em>. Thus here, the vector contains only two elements (one for each of the two species); it holds only these values, but will do so repeatedly, at each time point. Only the output will contain all of the population sizxes through time.</p>
<p>To integrate these populations, we need to specify new initial conditions, and new parameters for the two-species model.</p>
<div class="sourceCode" id="cb553"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb553-1"><a href="appendix.html#cb553-1"></a>a &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="fl">0.02</span>, <span class="fl">0.01</span>, <span class="fl">0.01</span>, <span class="fl">0.03</span>), <span class="dt">nrow=</span><span class="dv">2</span>)</span>
<span id="cb553-2"><a href="appendix.html#cb553-2"></a>r &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>)</span>
<span id="cb553-3"><a href="appendix.html#cb553-3"></a>p2 &lt;-<span class="st"> </span><span class="kw">list</span>(r, a)</span>
<span id="cb553-4"><a href="appendix.html#cb553-4"></a>N0 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">10</span>,<span class="dv">10</span>)</span>
<span id="cb553-5"><a href="appendix.html#cb553-5"></a>t2 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">5</span>,<span class="dv">10</span>,<span class="dv">20</span>)</span>
<span id="cb553-6"><a href="appendix.html#cb553-6"></a>out &lt;-<span class="st"> </span><span class="kw">ode</span>(<span class="dt">y=</span>N0, <span class="dt">times=</span>t2, <span class="dt">func=</span>LVComp, <span class="dt">parms=</span>p2)</span>
<span id="cb553-7"><a href="appendix.html#cb553-7"></a>out[<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>,]</span></code></pre></div>
<pre><code>##      time        1        2
## [1,]    1 10.00000 10.00000
## [2,]    5 35.53914 21.79929
## [3,]   10 39.61141 20.35672
## [4,]   20 39.99332 20.00667</code></pre>
<div class="sourceCode" id="cb555"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb555-1"><a href="appendix.html#cb555-1"></a><span class="kw">plot</span>(out)</span></code></pre></div>
<p><img src="figs/unnamed-chunk-262-1.png" width="90%" /></p>
<p>The <code>ode</code> function is a wrapper for a variety of ODE solvers; the default <code>lsoda</code> is a well tested tool. In addition, it has several bells and whistles that we will not need to take advantage of here, although I will mention one,<code>hmax</code>. This tells <code>lsoda</code> the largest step it can take. Once in a great while, with a very <em>stiff</em> ODE (a very wiggly complex dynamic), ODE assumes it can take a bigger step than it should. Setting <code>hmax</code> to a smallish number will limit the size of the step to help ensure that the integration proceeds as it should.</p>
<p>One of the other solvers in the <code>deSolve</code>, <code>lsodar</code>, will also return roots (or equilibria), for a system of ODEs, if they exist. Here we find the roots (i.e. the solutions, or equilibria) for a two species enemy-victim model.</p>
<div class="sourceCode" id="cb556"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb556-1"><a href="appendix.html#cb556-1"></a>EV &lt;-<span class="st"> </span><span class="cf">function</span>(t, y, p){</span>
<span id="cb556-2"><a href="appendix.html#cb556-2"></a>  <span class="kw">with</span>(<span class="kw">as.list</span>(p), {</span>
<span id="cb556-3"><a href="appendix.html#cb556-3"></a>    dv.dt &lt;-<span class="st"> </span>b <span class="op">*</span><span class="st"> </span>y[<span class="dv">1</span>]<span class="op">*</span>(<span class="dv">1</span><span class="fl">-.005</span><span class="op">*</span>y[<span class="dv">1</span>]) <span class="op">-</span><span class="st"> </span>a<span class="op">*</span>y[<span class="dv">1</span>]<span class="op">*</span>y[<span class="dv">2</span>]</span>
<span id="cb556-4"><a href="appendix.html#cb556-4"></a>    de.dt &lt;-a<span class="op">*</span>e<span class="op">*</span>y[<span class="dv">1</span>]<span class="op">*</span>y[<span class="dv">2</span>] <span class="op">-</span><span class="st"> </span>s<span class="op">*</span>y[<span class="dv">2</span>]</span>
<span id="cb556-5"><a href="appendix.html#cb556-5"></a>    <span class="kw">return</span>( <span class="kw">list</span>( <span class="kw">c</span>(dv.dt, de.dt) ) )</span>
<span id="cb556-6"><a href="appendix.html#cb556-6"></a>  } )</span>
<span id="cb556-7"><a href="appendix.html#cb556-7"></a>}</span></code></pre></div>
<p>To use <code>lsodar</code> to find equilibria, we need to specify a root finding function whose inputs are are the sme of the ODE function, and which returns a scalar (a single number) that determines whether the rate of change (<span class="math inline">\(dy/dx\)</span>) is sufficiently close to zero that we can say that the system has stopped changed, that is, has reached a steady state or equilibrium. Here we sum the absolute rates of change of each species, and then subtract 10<span class="math inline">\(^{-10}\)</span>; if that difference is zero, we decide that, for all pratcial purposes, the system has stopped changing.</p>
<div class="sourceCode" id="cb557"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb557-1"><a href="appendix.html#cb557-1"></a>rootfun &lt;-<span class="st"> </span><span class="cf">function</span> (t,y,p) { </span>
<span id="cb557-2"><a href="appendix.html#cb557-2"></a>dstate &lt;-<span class="st"> </span><span class="kw">unlist</span>(<span class="kw">EV</span>(t,y,p)) <span class="co">#rate of change vector </span></span>
<span id="cb557-3"><a href="appendix.html#cb557-3"></a><span class="kw">return</span>(<span class="kw">sum</span>(<span class="kw">abs</span>(dstate))<span class="op">-</span><span class="fl">1e-10</span>) </span>
<span id="cb557-4"><a href="appendix.html#cb557-4"></a>} </span></code></pre></div>
<p>Note that <code>unlist</code> changes the <code>list</code> returned by <code>EV</code> into a simple vector, which can then be summed.</p>
<p>Next we specify parameters, and time. Here all we want is the root, so we specify that we want the value of <span class="math inline">\(y\)</span> after a really long time (<span class="math inline">\(t=10^{10}\)</span>). The <code>lsodar</code> function will stop sooner than that, and return the equilibrium it finds, and the time step at which it occurred.</p>
<div class="sourceCode" id="cb558"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb558-1"><a href="appendix.html#cb558-1"></a>p &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dt">b =</span> <span class="fl">0.5</span>, <span class="dt">a =</span> <span class="fl">0.02</span>, <span class="dt">e=</span><span class="fl">0.1</span>, <span class="dt">s=</span><span class="fl">0.2</span>)</span>
<span id="cb558-2"><a href="appendix.html#cb558-2"></a>t &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>,<span class="fl">1e10</span>)</span></code></pre></div>
<p>Now we run the function.</p>
<div class="sourceCode" id="cb559"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb559-1"><a href="appendix.html#cb559-1"></a>out &lt;-<span class="st"> </span><span class="kw">ode</span>(<span class="dt">y=</span><span class="kw">c</span>(<span class="dv">45</span>,<span class="dv">200</span>), t, EV, <span class="dt">parms=</span>p, <span class="dt">rootfun=</span>rootfun, <span class="dt">method=</span><span class="st">&quot;lsodar&quot;</span>)</span>
<span id="cb559-2"><a href="appendix.html#cb559-2"></a>out[,]</span></code></pre></div>
<pre><code>##          time   1     2
## [1,]   0.0000  45 200.0
## [2,] 500.8094 100  12.5</code></pre>
<p>Here we see that the steady state population sizes are <span class="math inline">\(V=100\)</span> and <span class="math inline">\(E=12.5\)</span>, and that given our starting point, this steady state was achieved at <span class="math inline">\(t=500.8\)</span>. Other information is available; see <code>?lsodar</code> after loading the <code>deSolve</code> package.</p>
<p>We can also find the equilibrium or steady state using the <code>rootSolve</code> package.</p>
<div class="sourceCode" id="cb561"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb561-1"><a href="appendix.html#cb561-1"></a><span class="kw">library</span>(rootSolve)</span>
<span id="cb561-2"><a href="appendix.html#cb561-2"></a>equil &lt;-<span class="st"> </span><span class="kw">runsteady</span>(<span class="dt">y=</span><span class="kw">c</span>(<span class="dv">45</span>,<span class="dv">200</span>), <span class="dt">times=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="fl">1E5</span>), <span class="dt">func=</span>EV, <span class="dt">parms=</span>p)</span>
<span id="cb561-3"><a href="appendix.html#cb561-3"></a><span class="kw">round</span>(equil<span class="op">$</span>y, <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] 100.0  12.5</code></pre>
</div>
<div id="eigenanalysis" class="section level2">
<h2><span class="header-section-number">14.6</span> Eigenanalysis</h2>
<p>Performing eigenanalysis in R is easy. We use the  function which returns a list with two components. The first named component is a vector of eigenvalues and the second named component is a matrix of corresponding eigenvectors. These will be numeric if possible, or complex, if any of the elements are complex numbers.</p>
<p>Here we have a typical demographic stage matrix.</p>
<div class="sourceCode" id="cb563"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb563-1"><a href="appendix.html#cb563-1"></a>A &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">.1</span>, <span class="dv">10</span>, <span class="fl">.5</span>), <span class="dt">nrow=</span><span class="dv">2</span>)</span>
<span id="cb563-2"><a href="appendix.html#cb563-2"></a>eig.A &lt;-<span class="st"> </span><span class="kw">eigen</span>(A)</span>
<span id="cb563-3"><a href="appendix.html#cb563-3"></a><span class="kw">str</span>(eig.A)</span></code></pre></div>
<pre><code>## List of 2
##  $ values : num [1:2] 1.281 -0.781
##  $ vectors: num [1:2, 1:2] -0.9919 -0.127 -0.997 0.0778
##  - attr(*, &quot;class&quot;)= chr &quot;eigen&quot;</code></pre>
<p>Singular value decomposition (SVD) is a generalization of eigenanalysis and is used in R for some applications where eigenanalysis was used historically, but where SVD is more numerically accurate ( for principle components analysis).</p>
<div id="eigenanalysis-of-demographic-versus-jacobian-matrices" class="section level3">
<h3><span class="header-section-number">14.6.1</span> Eigenanalysis of demographic versus Jacobian matrices</h3>
<p>Eigenanalyses of demographic and Jacobian matrices are worth comparing. In one sense, they have similar meanings — they both describe the asymptotic (long-term) properties of a system, either population size (demographic matrix) or a perturbation at an equilibrium. The quantitative interpretation of the eigenvalues will therefore differ.</p>
<p>In the case of the stage (or age) structured demographic model, the elements of the demographic matrix are discrete per capita increments of change over a specified time interval. This is directly analogous to the finite rate of increase, <span class="math inline">\(\lambda\)</span>, in discrete unstructured models. (Indeed, an unstructured discrete growth model is a stage-structured model with one stage). Therefore, the eigenvalues of a demographic matrix will have the same units — a per capita increment of change. That is why the dominant eigenvalue has to be greater than 1.0 for the population to increase, and less than 1 (not merely less than zero) for the population to decline.</p>
<p>In the case of the Jacobian matrix, comprised of continuous partial differential equations, the elements are per capita <em>instantaneous</em> rates of change. As differential equations, they describe the <em>instantanteous</em> rates of change, analogous to <span class="math inline">\(r\)</span>. Therefore, values greater than zero indicate increases, and values less than zero indicate decreases. Because these rates are evaluated at an equilibrium, the equilibrium acts like a new zero — positive values indicate growth away from the equilibrium, and negative values indicate shrinkage back toward the equilibrium. When we evaluate these elements at the equilibrium, the numbers we get are in the same units as <span class="math inline">\(r\)</span>, where values greater than zero indicate increase, and values less than zero indicate decrease. The change they describe is the instantaneous per capita rate of change of each population with respect to the others. The eigenvalues summarizing all of the elements Jacobian matrix thus must be less than zero for the disturbance to decline.</p>
<p>So, in summary, the elements of a demographic matrix are discrete increments over a real time interval. Therefore its eigenvalues represent relative per capita growth rates a discrete time interval, and we interpret the eigenvalues with respect to 1.0. On the other hand, the elements of the Jacobian matrix are instantaneous per captia rates of change evaluated at an equilibrium. Therefore its eigenvalues represent the per capita <em>instantaneous</em> rates of change of a tiny perturbation at the equilibrium. We interpret the eigenvalues with respect to 0 indicating whether the perturbation grows or shrinks.</p>
</div>
</div>
<div id="derivation-of-the-right-eigenvalues" class="section level2">
<h2><span class="header-section-number">14.7</span> Derivation of the right eigenvalues</h2>
<p><span class="math display">\[\begin{align*}
Aw &amp;=\lambda w\\
Aw-\lambda w &amp;=0\\
Aw - \lambda I w  &amp;=\mathbf{0} \\
\left(A - \lambda I\right)w  &amp;=0 
\end{align*}\]</span></p>
<p>By rules of determinants, it follows then that,
<span class="math display">\[\mathrm{det} \left| A - \lambda I \right| =0\]</span></p>
<p>And here is an empirical example.</p>
<div class="sourceCode" id="cb565"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb565-1"><a href="appendix.html#cb565-1"></a>A &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>, <span class="dt">nrow=</span><span class="dv">2</span>)</span>
<span id="cb565-2"><a href="appendix.html#cb565-2"></a>lambda &lt;-<span class="st"> </span><span class="kw">eigen</span>(A)<span class="op">$</span>values[<span class="dv">1</span>]</span>
<span id="cb565-3"><a href="appendix.html#cb565-3"></a>w &lt;-<span class="st"> </span><span class="kw">eigen</span>(A)<span class="op">$</span>vectors[,<span class="dv">1</span>]</span>
<span id="cb565-4"><a href="appendix.html#cb565-4"></a>I &lt;-<span class="st"> </span><span class="kw">diag</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb565-5"><a href="appendix.html#cb565-5"></a><span class="kw">round</span>(lambda<span class="op">*</span>w <span class="op">-</span><span class="st"> </span>A<span class="op">%*%</span>w, <span class="dv">4</span>)</span></code></pre></div>
<pre><code>##      [,1]
## [1,]    0
## [2,]    0</code></pre>
<div class="sourceCode" id="cb567"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb567-1"><a href="appendix.html#cb567-1"></a><span class="kw">round</span>(lambda<span class="op">*</span>I<span class="op">%*%</span>w <span class="op">-</span><span class="st"> </span>A<span class="op">%*%</span>w, <span class="dv">4</span>)</span></code></pre></div>
<pre><code>##      [,1]
## [1,]    0
## [2,]    0</code></pre>
<div class="sourceCode" id="cb569"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb569-1"><a href="appendix.html#cb569-1"></a><span class="kw">round</span>((lambda<span class="op">*</span>I <span class="op">-</span><span class="st"> </span>A)<span class="op">%*%</span>w, <span class="dv">4</span>)</span></code></pre></div>
<pre><code>##      [,1]
## [1,]    0
## [2,]    0</code></pre>
<div class="sourceCode" id="cb571"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb571-1"><a href="appendix.html#cb571-1"></a><span class="kw">det</span>( lambda<span class="op">*</span>I<span class="op">-</span>A )</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>Once we know that the determinant is zero, we can use that to create a simple quadratic equation in terms of <span class="math inline">\(\lambda\)</span>, and then solve. First, let’s remember what the above difference is:
<span class="math display">\[\mathbf{A} - \lambda\mathbf{I} = \begin{pmatrix} 
a-\lambda &amp; b \\
c &amp; d - \lambda
\end{pmatrix}\]</span></p>
<p>Then we can use the determinant to solve for lambda.
<span class="math display">\[ \mathrm{det} \begin{pmatrix} 
a-\lambda &amp; b \\
c &amp; d - \lambda
\end{pmatrix} = (a-\lambda)(d-\lambda) - bc = 0\]</span>
<span class="math display">\[\lambda^2 - (a+d)\lambda + (ad-bc) = 0\]</span>
<span class="math display">\[\lambda = \frac{-(a+d) \pm \sqrt{(a+d)^2 - 4(ad-bc)}}{2}\]</span>
And that is one way to find the two eigenvalues of a <span class="math inline">\(2 \times 2\)</span> matrix, whether it is a demographic projection matrix, predator-prey interaction matrix, or something else.</p>
</div>
<div id="symbols-used-in-this-book" class="section level2">
<h2><span class="header-section-number">14.8</span> Symbols used in this book</h2>
<p>I am convinced that one of the biggest hurdles to learning theoretical ecology — and the one that is easiest to overcome — is to be able to “read” and hear them in your head. This requires being able to pronounce Greek symbols. Few of us learned how to pronounce <span class="math inline">\(\alpha\)</span> in primary school. Therefore, I provide here an incomplete simplistic American English pronunciation guide for (some of) the rest of us, for symbols in this book. Only a few are tricky, and different people will pronounce them differently.</p>
<p>Symbols and their pronunciation; occasional usage applies to lowercase, unless otherwise specified. A few symbols have common variants. Any symbol might be part of any equation; ecologists frequently ascribe other meanings which have to be defined each time they are used.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:greek">Table 14.1: </span>Symbols and their pronunciation; occasional usage applies to lowercase, unless otherwise specified. A few symbols have common variants. Any symbol might be part of any equation; ecologists frequently ascribe other meanings which have to be defined each time they are used.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Greek Symbol
</th>
<th style="text-align:left;">
Spelling and pronunciation
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
A, <span class="math inline">\(\alpha\)</span>
</td>
<td style="text-align:left;">
alpha; al’-fa; point or local diversity (or a parameter in the logseries abundance distribution)
</td>
</tr>
<tr>
<td style="text-align:left;">
B, <span class="math inline">\(\beta\)</span>
</td>
<td style="text-align:left;">
beta; bay’-ta; turnover diversity
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\mathrm{\Gamma}\)</span>, <span class="math inline">\(\gamma\)</span>
</td>
<td style="text-align:left;">
gamma; gam’-ma; regional diversity
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\mathrm{\Delta}\)</span>, <span class="math inline">\(\delta\)</span>, <span class="math inline">\(\partial\)</span>
</td>
<td style="text-align:left;">
delta; del’-ta; change or difference
</td>
</tr>
<tr>
<td style="text-align:left;">
E, <span class="math inline">\(\epsilon\)</span>, <span class="math inline">\(\varepsilon\)</span>
</td>
<td style="text-align:left;">
epsilon; ep’-si-lon; error
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\mathrm{\Theta}\)</span>, <span class="math inline">\(\theta\)</span>
</td>
<td style="text-align:left;">
theta; thay’-ta (‘th’ as in ‘thanks’); in neutral theory, biodiversity
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\mathrm{\Lambda}\)</span>, <span class="math inline">\(\lambda\)</span>
</td>
<td style="text-align:left;">
lambda; lam’-da; eigenvalues, and finite rate of increase
</td>
</tr>
<tr>
<td style="text-align:left;">
M, <span class="math inline">\(\mu\)</span>
</td>
<td style="text-align:left;">
mu; meeoo, myou; mean
</td>
</tr>
<tr>
<td style="text-align:left;">
N, <span class="math inline">\(\nu\)</span>
</td>
<td style="text-align:left;">
nu; noo, nou
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\mathrm{\Pi}\)</span>, <span class="math inline">\(\pi\)</span>
</td>
<td style="text-align:left;">
pi; pie; uppercase for product (of the elements of a vector)
</td>
</tr>
<tr>
<td style="text-align:left;">
P, <span class="math inline">\(\rho\)</span>
</td>
<td style="text-align:left;">
rho; row (as in ‘a boat’); correlation
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\mathrm{\Sigma}\)</span>, <span class="math inline">\(\sigma\)</span>, <span class="math inline">\(\varsigma\)</span>
</td>
<td style="text-align:left;">
sigma; sig’-ma; standard deviation (uppercase is used for summation)
</td>
</tr>
<tr>
<td style="text-align:left;">
T, <span class="math inline">\(\tau\)</span>
</td>
<td style="text-align:left;">
tau; (sounds like what you say when you stub your toe - ‘Ow!’ but with a ‘t’).
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\Phi\)</span>, <span class="math inline">\(\phi\)</span>
</td>
<td style="text-align:left;">
phi; fie, figh
</td>
</tr>
<tr>
<td style="text-align:left;">
X, <span class="math inline">\(\chi\)</span>
</td>
<td style="text-align:left;">
chi; kie, kigh
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\mathrm{\Psi}\)</span>, <span class="math inline">\(\psi\)</span>
</td>
<td style="text-align:left;">
psi; sie, sigh
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\mathrm{\Omega}\)</span>, <span class="math inline">\(\omega\)</span>
</td>
<td style="text-align:left;">
omega; oh-may’-ga; degree of omnivory
</td>
</tr>
</tbody>
</table>

</div>
</div>
<h3> References</h3>
<div id="refs" class="references">
<div id="ref-Petzoldt:2003dp">
<p>Petzoldt, T. 2003. “R as a simulation platform in ecological modelling.” <em>R News</em> 3: 8–16.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="81">
<li id="fn81"><p>There are other methods we could use. These are discussed by others, under various topics, including “flow control.” We use ODE solvers for continuous ordinary differential equations.<a href="appendix.html#fnref81" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="diversity.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
